name: bgl-env
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - pandas<2.0.0
      - numpy<2.0.0
      - scikit-learn==1.0.2
      - mlflow
      - azureml-mlflow
      - pyarrow
